EFS/efsd2/efs/efs/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, re_path
from django.contrib.auth import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'', include('django.contrib.auth.urls')),
]

EFS/efsd2/efs/portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeDoneView

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('signup/', views.register, name='register'),
    path('login/password-reset/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),
    path('reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_success.html'),
         name='password_success'),
    path('reset/OA/set-password/', auth_views.PasswordResetView.as_view(template_name='registration/reset_confirm.html'), name='reset_confirm'),
    path('login/change-password/',
         auth_views.PasswordChangeView.as_view(template_name='registration/change_password.html'),
         name='change_password'),
    path('password_change/done/',
         views.PasswordChangeDoneView.as_view(template_name='registration/password_success.html'),
         name='password_success'),
    path('mutual_list', views.mutual_list, name='mutual_list'),
    path('mutual/<int:pk>/edit/', views.mutual_edit, name='mutual_edit'),
    path('mutual/<int:pk>/delete/', views.mutual_delete, name='mutual_delete'),
    path('mutual/create/', views.mutual_new, name='mutual_new'),
    path('customer/portfolio/', views.customer_portfolio, name='customer_portfolio'),
 ]

EFS/efsd2/efs/portfolio/models.py
from django.db import models
from django.utils import timezone


# Create your models here.


class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value


class Stock(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField(max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_stock_value(self):
        return self.shares * self.purchase_price

class Mutual(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='mutuals')
    fund_category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    direct_plan = models.DecimalField(max_digits=10, decimal_places=2)
    regular_plan = models.DecimalField(max_digits=10, decimal_places=2)
    difference = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date  = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
            self.acquired_date = timezone.now()
            self.save()

    def updated(self):
            self.recent_date = timezone.now()
            self.save()

    def __str__(self):
            return str(self.customer)

        

EFS/efsd2/efs/portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment, Mutual
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value',
                  'recent_date',)


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class MutualForm(forms.ModelForm):
    class Meta:
        model = Mutual
        fields = ('customer', 'fund_category', 'description', 'direct_plan', 'regular_plan', 'difference', 'acquired_date',)

EFS/efsd2/efs/portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy


now = timezone.now()


def home(request):
    return render(request, 'portfolio/home.html',
                  {'portfolio': home})


@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                  {'customers': customer})


@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'portfolio/customer_list.html',
                          {'customers': customer})
    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'portfolio/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('portfolio:customer_list')


@login_required
def stock_list(request):
    stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
    return render(request, 'portfolio/stock_list.html', {'stocks': stocks})


@login_required
def stock_new(request):
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.created_date = timezone.now()
            stock.save()
            stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/stock_list.html',
                          {'stocks': stocks})
    else:
        form = StockForm()
        # print("Else")
    return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def stock_edit(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    if request.method == "POST":
        form = StockForm(request.POST, instance=stock)
        if form.is_valid():
            stock = form.save()
            # stock.customer = stock.id
            stock.updated_date = timezone.now()
            stock.save()
            stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
    else:
        # print("else")
        form = StockForm(instance=stock)
    return render(request, 'portfolio/stock_edit.html', {'form': form})


@login_required
def stock_delete(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    stock.delete()
    return redirect('portfolio:stock_list')


@login_required
def investment_new(request):
    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.created_date = timezone.now()
            investment.save()
            investments = Investment.objects.filter(acquired_date__lte=timezone.now())
            return render(request, 'portfolio/investment_list.html',
                          {'investments': investments})
    else:
        form = InvestmentForm()
        # print("Else")
    return render(request, 'portfolio/investment_new.html', {'form': form})


@login_required
def investment_list(request):
    investments = Investment.objects.filter(acquired_date__lte=timezone.now())
    return render(request, 'portfolio/investment_list.html', {'investments': investments})


@login_required
def investment_edit(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    if request.method == "POST":
        form = InvestmentForm(request.POST, instance=investment)
        if form.is_valid():
            investment = form.save()
            investment.updated_date = timezone.now()
            investment.save()
            investments = Investment.objects.filter(acquired_date__lte=timezone.now())
            return render(request, 'portfolio/investment_list.html', {'investments': investments})
    else:
        # print("else")
        form = InvestmentForm(instance=investment)
    return render(request, 'portfolio/investment_edit.html', {'form': form})


@login_required
def investment_delete(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    investment.delete()
    return redirect('portfolio:investment_list', )

@login_required
def mutual_new(request):
    if request.method == "POST":
        form = MutualForm(request.POST)
        if form.is_valid():
            mutual = form.save(commit=False)
            mutual.created_date = timezone.now()
            mutual.save()
            mutuals = Mutual.objects.filter(acquired_date__lte=timezone.now())
            return render(request, 'portfolio/mutual_list.html',
                          {'mutuals': mutuals})
    else:
        form = MutualForm()
        # print("Else")
    return render(request, 'portfolio/mutual_new.html', {'form': form})


@login_required
def mutual_list(request):
    mutuals = Mutual.objects.filter(acquired_date__lte=timezone.now())
    return render(request, 'portfolio/mutual_list.html', {'mutuals': mutuals})


@login_required
def mutual_edit(request, pk):
    mutual = get_object_or_404(Mutual, pk=pk)
    if request.method == "POST":
        form = MutualForm(request.POST, instance=mutual)
        if form.is_valid():
            mutual = form.save()
            mutual.updated_date = timezone.now()
            mutual.save()
            mutuals = Mutual.objects.filter(acquired_date__lte=timezone.now())
            return render(request, 'portfolio/mutual_list.html', {'mutuals': mutuals})
    else:
        # print("else")
        form = MutualForm(instance=mutual)
    return render(request, 'portfolio/mutual_edit.html', {'form': form})


@login_required
def mutual_delete(request, pk):
    mutual = get_object_or_404(Mutual, pk=pk)
    mutual.delete()
    return redirect('portfolio:mutual_list', )

# views.py


# Create your views here.
def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()

        return redirect("/home")
    else:
        form = RegisterForm()

    return render(response, "portfolio/register.html", {"form": form})


class PasswordsChangeView(PasswordChangeView):
    from_class = PasswordChangeForm
    success_url = reverse_lazy('password_success')

def customer_portfolio(request):
        labels = []
        data = []

        queryset = Investment.objects.order_by('-recent_value')[:5]
        for investment in queryset:
            labels.append(investment.category)
            data.append(investment.recent_value)

        return render(request, 'portfolio/customer_portfolio.html', {
            'labels': labels,
            'data': data,
        })

EFS/efsd2/efs/portfolio/templates/portfolio/base.html
{% load static %}

<html lang="en">
<head>
<title>Eagle Financial Services</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eagle Financial Services</title>
 <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>

 <style>
        body,html{
            height: 100%;
            margin: 0;
            background: #7F7FD5;
            background: -webkit-linear-gradient(to right, #536366, #999d9e);
            background: linear-gradient(to right, #999d9e, #2892ad);
        }
        #events_card{
            padding-bottom: 40px;
        }
    </style>
<body>
 <button class="navbar-toggler" type="button" data-toggle="collapse"  data-target="#navbarCollapse" aria-controls="navbarCollapse"  aria-expanded="false" aria-label="Toggle navigation"> 
        <span class="navbar-toggler-icon">
        </span>
           </button> 
 <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
           <a class="navbar-brand" href="/">Eagle Financial Services</a> 
    {% if user.is_authenticated %} 
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item lead"><a class=nav-link href="{% url 'portfolio:home' %}">Home</a></li>
                <li class="nav-item lead"><a class=nav-link href="{% url 'portfolio:customer_list' %}">Customers</a></li>
                <li class="nav-item lead"><a class=nav-link href="{% url 'portfolio:investment_list' %}">Investment</a></li>
                <li class="nav-item lead"><a class=nav-link href="{% url 'portfolio:stock_list' %}">Stocks</a></li>
                <li class="nav-item lead"><a class=nav-link href="{% url 'portfolio:mutual_list' %}">Mutual Funds</a></li>

            </ul>

    {% endif %} 
    <div class="collapse navbar-collapse" id="navbarCollapse"> 
        {% if user.is_authenticated %} 
            <ul class="navbar-nav ml-auto"> 
                <li class="nav-item">
                                   <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                       {{ user.username }} 
                                   </a> 
                    <div class="dropdown-menu dropdown-menu-right"  aria-labelledby="userMenu">
                                         <a class="dropdown-item" href="{% url  'portfolio:change_password'  %}">Change password</a> 
                        <div class="dropdown-divider">

                        </div> 
                        <a class="dropdown-item" href="{% url 'logout' %}"> Log Out</a> 
                    </div> 
                </li> 
            </ul> 
        {% else %} 
            <form class="form-inline ml-auto"> 
                <a href="{% url 'login' %}" class="btn btn-outline-secondary"> Log In</a>
                             <a class="navbar-brand" href="{% url 'portfolio:register' %}"> Sign Up </a>


            </form> 
        {% endif %} 
    </div> 
</nav> 

<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/customer.jpg" %}" alt="customers"/>
                                <div class="caption">
                                    <h2>Customer</h2>
                                    <p>We see our success in our customers success, it gives us an immense pleasure when
                                        our
                                        advises
                                        turn out to be fruitful. </p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-dark" href="{% url 'portfolio:customer_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
<img src="{% static "images/nonstock.jpg" %}" alt="non-stock"/>
                                <div class="caption">
                                    <h2>Non-Stock Investments</h2>
                                    <p>Our team also provides advice for Non-Stock investments.</p>
                                    <p><a class="btn btn-dark" href="{% url 'portfolio:investment_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
 <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/stocks.jpg" %}" alt="stocks"/>
                                <div class="caption">
                                    <h2>Stock Portfolio</h2>
                                    <p>Our Stock portfolios vary across industries.</p>
                                    <p><a class="btn btn-dark" href="{% url 'portfolio:stock_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
<div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/mutualfunds.jpg" %}" alt="mutual"/>
                                <div class="caption">
                                    <h2>Mutual Funds</h2>
                                    <p><a class="btn btn-dark" href="{% url 'portfolio:mutual_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</div>

</div>

</body>

</html>

EFS/efsd2/efs/portfolio/templates/portfolio/customer_delete.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ customer.name }}"?</p>
      <button class="btn btn-dark" type="submit">Confirm</button>
    </form>
{% endblock content %}

EFS/efsd2/efs/portfolio/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h1>Edit Customer</h1>
       <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-dark">Update</button>
    </form>
</body>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/customer_portfolio.html
{% extends 'portfolio/base.html' %}

{% block content %}
  <div id="container" style="width: 75%;">
    <canvas id="pie-chart"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    var config = {
      type: 'pie',
      data: {
        datasets: [{
          data: {{ data|safe }},
          backgroundColor: [
            '#696969', '#808080', '#A9A9A9', '#C0C0C0', '#D3D3D3'
          ],
          label: 'Investments'
        }],
        labels: {{
          labels|safe }}
      },
      options: {
        responsive: true
      }
    };

    window.onload = function() {
      var ctx = document.getElementById('pie-chart').getContext('2d');
      window.myPie = new Chart(ctx, config);
    };

  </script>

{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/investment_delete.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ customer.name }}"?</p>
      <button class="btn btn-dark" type="submit">Confirm</button>
    </form>
{% endblock content %}

EFS/efsd2/efs/portfolio/templates/portfolio/investment_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h1>Edit Investment</h1>
       <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Update</button>
    </form>
</body>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/investment_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<body>

    <h1>Add a New Investment</h1>
    <form method="POST" class="investment-form">{% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="save btn btn-dark">Save</button>
    </form>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/mutual_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h1>Edit Mutual</h1>
       <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Update</button>
    </form>
</body>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/mutual_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html lang="en">
    <body>

    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
  <header class="jumbotron jumbotron-fluid" style="background: white">
      <p class="lead text-nowrap"><b>Eagle Financial Services, your Midwest Financial Services Partner</b></p>
         </header>
    <div class="row">
        <h2 style="padding-left: 15Px"><u>Mutual Funds Information</u></h2>
    </div>
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
            <tr bgcolor="white">
                <th>Customer number</th>
                <th>Fund Category</th>
                <th>Description</th>
                <th>Direct Plan</th>
                <th>Regular Plan</th>
                <th>Difference(Regular-Direct)</th>
                <th>Acquired date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for mutual in mutuals %}
                <tr bgcolor="white">
                    <td>{{mutual.customer }}</td>
                    <td>{{mutual.fund_category }}</td>
                    <td>{{mutual.description }}</td>
                    <td>{{mutual.direct_plan}}</td>
                    <td>{{mutual.regular_plan }}</td>
                    <td>{{mutual.difference }}</td>
                    <td>{{mutual.acquired_date}}</td>

                    <td><a href="{% url 'portfolio:mutual_edit' pk=mutual.pk %}"
                           class=" btn btn-dark">Edit</a></td>
                    <td><a href="{% url 'portfolio:mutual_delete' pk=mutual.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    class=" btn btn-dark">Delete</a>
                    </td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>

     <div class="row">
            <a href="{% url 'portfolio:mutual_new' %}" class="row"><span
                    class="btn btn-dark">Add Mutual Funds</span></a>
        </div>

    </div>
    </body>
    </html>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/register.html
{% extends "portfolio/base.html" %}

{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" class="form-group">
	{% csrf_token %}
	{{ form|crispy }}
	<button type="submit" class="btn btn-dark">Submit</button>
    </form>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/stock_delete.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Are you sure you want to delete "{{ customer.name }}"?</p>
      <button class="btn btn-dark" type="submit">Confirm</button>
    </form>
{% endblock content %}

EFS/efsd2/efs/portfolio/templates/portfolio/stock_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h1>Edit Stock</h1>
       <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Update</button>
    </form>
</body>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/stock_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html lang="en">
    <body>

    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
  <header class="jumbotron jumbotron-fluid" style="background: white">
      <p class="lead text-nowrap"><b>Eagle Financial Services, your Midwest Financial Services Partner</b></p>
         </header>
    <div class="row">
        <h2 style="padding-left: 15Px"><u>Stocks Information</u></h2>
    </div>
    <div>
        <table class="table table-hover table-responsive-lg text-center">
            <thead>
            <tr bgcolor="white">
                <th>Customer number</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Shares</th>
                <th>Purchase Price</th>
                <th>Purchase Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for stock in stocks %}
                <tr bgcolor="white">
                    <td>{{ stock.customer }}</td>
                    <td>{{ stock.symbol }}</td>
                    <td>{{ stock.name }}</td>
                    <td>{{ stock.shares }}</td>
                    <td>{{ stock.purchase_price }}</td>
                    <td>{{ stock.purchase_date }}</td>
                    <td><a href="{% url 'portfolio:stock_edit' pk=stock.pk %}"
                           class="btn btn-dark">Edit</a></td>
                    <td><a href="{% url 'portfolio:stock_delete' pk=stock.pk %}"
                    onclick="return confirm('Are you sure you want to delete?')"
                    class="btn btn-dark">Delete</a>
                    </td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>

     <div class="row">
            <a href="{% url 'portfolio:stock_new' %}" class="row"><span
                    class="btn btn-dark">Add Stock</span></a>
        </div>

    </div>
    </body>
    </html>
{% endblock %}

EFS/efsd2/efs/portfolio/templates/portfolio/stock_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<body>

    <h1>Add a New Stock</h1>
    <form method="POST" class="stock-form">{% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="save btn btn-dark">Save</button>
    </form>
{% endblock %}
</body>